# Generated by Django 6.0.6 on 2026-06-20 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_workspacefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Design', max_length=200)),
                ('canvas_json', models.TextField(default='{}')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='designs/thumbnails/')),
                ('canvas_width', models.IntegerField(default=1080)),
                ('canvas_height', models.IntegerField(default=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
